# Generated by Django 4.2.3 on 2023-08-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0006_alter_newspaper_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsPaper',
            new_name='Newsletter',
        ),
    ]
